// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { join } from 'path';
import { defineConfig } from 'prisma/config';

const envFiles = [join(process.cwd(), '.env'), join(process.cwd(), 'backend', '.env')];
for (const envPath of envFiles) {
  dotenv.config({ path: envPath, override: false });
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Prefer a direct DB connection when available (avoids pgbouncer/pgbouncer prepared-statement issues during migrations)
    url: process.env['DIRECT_URL'] || process.env['DATABASE_URL'],
    // @ts-ignore
    directUrl: process.env['DIRECT_URL'],
  },
});
